import React, { useState } from 'react';
import { PackageOpen, FileText, DollarSign, Send, CheckCircle2 } from 'lucide-react';

export default function HowItWorks() {
  const [activeStep, setActiveStep] = useState(0);

  const timelineSteps = [
    {
      id: 0,
      icon: <PackageOpen size={20} />,
      title: 'Select USDT',
      subtitle: 'CHOOSE PACKAGE',
      description: 'Review our pricing table and select which amount of Flash USDT best fits your testing or volume requirements.'
    },
    {
      id: 1,
      icon: <FileText size={20} />,
      title: 'Accept Terms',
      subtitle: 'CONFIRM T&C',
      description: 'Read, verify, and digitally approve the software licensing and network usage conditions of our platform.'
    },
    {
      id: 2,
      icon: <DollarSign size={20} />,
      title: 'Pay USDT',
      subtitle: 'NETWORK DEPOSIT',
      description: 'Send the corresponding order cost to the secure platform deposit wallet address generated by the wizard.'
    },
    {
      id: 3,
      icon: <Send size={20} />,
      title: 'Send Details',
      subtitle: 'DISPATCH METADATA',
      description: 'Input your target receiving wallet address, transaction ID hash, and email into our checkout form.'
    },
    {
      id: 4,
      icon: <CheckCircle2 size={20} />,
      title: 'Check Wallet',
      subtitle: 'RECEIVE FLASH',
      description: 'Our automated validator nodes confirm your deposit and transfer the Flash USDT straight to your wallet within 15 minutes.'
    }
  ];

  return (
    <section id="roadmap" className="py-24 relative select-none bg-black/25">
      {/* Background neon dots */}
      <div className="absolute top-[10%] right-[10%] w-72 h-72 bg-green-500/5 rounded-full blur-[100px] pointer-events-none" />

      <div className="max-w-7xl mx-auto px-6">
        
        {/* Header */}
        <div className="text-center max-w-2xl mx-auto mb-20 space-y-4">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-green-500/10 border border-green-500/20 text-green-400 font-mono text-[9px] uppercase tracking-widest">
            <span>OPERATIONAL PROCESS</span>
          </div>
          <h2 className="text-3xl md:text-4xl font-extrabold uppercase font-mono tracking-tight text-white">
            How Flasher <br/>
            <span className="bg-gradient-to-r from-green-500 to-emerald-400 bg-clip-text text-transparent neon-text-green">
              Works Step-by-Step
            </span>
          </h2>
          <p className="text-zinc-400 text-sm md:text-base leading-relaxed">
            A fully automated, streamlined, five-stage process designed to log details, process transaction hashes, and trigger node transfers instantly.
          </p>
        </div>

        {/* Interactive Desktop Timeline Flow */}
        <div className="hidden lg:block relative mb-16">
          {/* Animated Connecting Line */}
          <div className="absolute top-10 left-[8%] right-[8%] h-[2px] bg-zinc-800 -z-10">
            <div 
              className="h-full bg-gradient-to-r from-green-500 to-emerald-400 transition-all duration-700 ease-out shadow-[0_0_8px_rgba(34,197,94,0.6)]"
              style={{ width: `${(activeStep / (timelineSteps.length - 1)) * 100}%` }}
            />
          </div>

          <div className="grid grid-cols-5 gap-4">
            {timelineSteps.map((step) => {
              const isCompleted = step.id < activeStep;
              const isActive = step.id === activeStep;
              
              return (
                <div 
                  key={step.id}
                  className="flex flex-col items-center text-center cursor-pointer group"
                  onMouseEnter={() => setActiveStep(step.id)}
                >
                  {/* Glowing step bubble */}
                  <div 
                    className={`w-20 h-20 rounded-2xl flex items-center justify-center border transition-all duration-500 relative z-10
                      ${isActive 
                        ? 'bg-zinc-900 border-green-500 text-green-400 shadow-[0_0_20px_rgba(34,197,94,0.4)] scale-110' 
                        : isCompleted
                          ? 'bg-green-500/10 border-green-500/40 text-green-500' 
                          : 'bg-zinc-950 border-zinc-800 text-zinc-500 hover:border-zinc-700 hover:text-zinc-300'
                      }`}
                  >
                    {/* Corner index tag */}
                    <span className="absolute -top-1.5 -right-1.5 w-6 h-6 rounded-md bg-zinc-900 border border-zinc-850 flex items-center justify-center font-mono text-[9px] text-zinc-500 font-bold group-hover:border-zinc-700">
                      0{step.id + 1}
                    </span>
                    {step.icon}
                  </div>

                  {/* Title & subtitle */}
                  <div className="mt-6 space-y-1">
                    <span className="block text-[8px] font-mono tracking-widest text-zinc-500 font-bold uppercase">{step.subtitle}</span>
                    <h3 className={`text-sm font-bold uppercase font-mono tracking-wide transition-colors duration-300 ${isActive ? 'text-green-400' : 'text-white'}`}>
                      {step.title}
                    </h3>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Detailed Active Step Description panel (Desktop) */}
        <div className="hidden lg:block glass-panel rounded-3xl p-8 border border-zinc-800/80 max-w-3xl mx-auto text-left relative overflow-hidden shadow-[0_15px_30px_rgba(0,0,0,0.3)]">
          <div className="absolute top-0 right-0 w-1/3 h-full bg-gradient-to-l from-green-500/2 to-transparent pointer-events-none" />
          
          <div className="flex gap-6 items-start">
            <div className="p-4 bg-green-500/10 border border-green-500/20 text-green-400 rounded-2xl">
              {timelineSteps[activeStep].icon}
            </div>
            <div className="space-y-2">
              <span className="block text-[10px] font-mono tracking-widest text-green-500 font-bold uppercase">
                STAGE_0{activeStep + 1} // {timelineSteps[activeStep].subtitle}
              </span>
              <h4 className="text-lg font-bold text-white uppercase font-mono tracking-wider">
                {timelineSteps[activeStep].title}
              </h4>
              <p className="text-zinc-400 text-sm leading-relaxed">
                {timelineSteps[activeStep].description}
              </p>
            </div>
          </div>
        </div>

        {/* Adaptive Vertical Flow (Mobile / Tablet) */}
        <div className="lg:hidden flex flex-col gap-8 relative">
          {/* Vertical progress line */}
          <div className="absolute left-[27px] top-4 bottom-4 w-[2px] bg-zinc-800 -z-10" />

          {timelineSteps.map((step) => {
            return (
              <div 
                key={step.id} 
                className="flex gap-6 text-left items-start group"
              >
                {/* Step bubble icon */}
                <div className="w-14 h-14 shrink-0 rounded-xl bg-zinc-950 border border-zinc-800 text-zinc-400 flex items-center justify-center group-hover:border-green-500/50 group-hover:text-green-400 transition-all duration-300 relative z-10">
                  <span className="absolute -top-1 -right-1 w-5 h-5 rounded bg-zinc-900 border border-zinc-800 flex items-center justify-center font-mono text-[8px] text-zinc-500 font-bold">
                    0{step.id + 1}
                  </span>
                  {step.icon}
                </div>

                {/* Step Copy details */}
                <div className="space-y-1.5">
                  <span className="block text-[8px] font-mono tracking-widest text-zinc-500 font-bold uppercase">{step.subtitle}</span>
                  <h3 className="text-sm font-bold uppercase font-mono tracking-wide text-white group-hover:text-green-400 transition-colors duration-300">
                    {step.title}
                  </h3>
                  <p className="text-zinc-400 text-xs leading-relaxed max-w-md">
                    {step.description}
                  </p>
                </div>
              </div>
            );
          })}
        </div>

      </div>
    </section>
  );
}
